<?php
define('CFG_SYSTEM_INTERNAL_ENCODING', 'UTF-8');

define('KKM_ERROR_CODE_0',  'Закройте лоток для денег');
define('KKM_ERROR_CODE_11', 'Переполнение счётчика наличности');
define('KKM_ERROR_CODE_19', 'Неверный формат');
define('KKM_ERROR_CODE_20', 'Неверная длина');
define('KKM_ERROR_CODE_21', 'ККМ заблокирована в режиме ввода даты');
define('KKM_ERROR_CODE_22', 'Требуется подтверждение ввода даты');
define('KKM_ERROR_CODE_26', 'Отчет с гашением прерван. Вход в режим невозможен');
define('KKM_ERROR_CODE_30', 'Вход в режим заблокирован');
define('KKM_ERROR_CODE_31', 'Проверьте дату и время');
define('KKM_ERROR_CODE_32', 'Дата и время в ККМ меньше чем в ЭКЛЗ/ФП');
define('KKM_ERROR_CODE_63', 'Переполнение буфера чека');
define('KKM_ERROR_CODE_102', 'Команда не реализуется в данном режиме ККМ');
define('KKM_ERROR_CODE_103', 'Нет бумаги');
define('KKM_ERROR_CODE_104', 'Нет связи с принтером чеков');
define('KKM_ERROR_CODE_115', 'Накопление меньше суммы возврата или аннулирования');
define('KKM_ERROR_CODE_122', 'Данная модель ККМ не может выполнить команду');
define('KKM_ERROR_CODE_127', 'Переполнение при умножении');
define('KKM_ERROR_CODE_130', 'Открыт чек аннулирования – операция невозможна');
define('KKM_ERROR_CODE_134', 'Вносимая клиентом сумма меньше суммы чека');
define('KKM_ERROR_CODE_135', 'Открыт чек возврата – операция невозможна');
define('KKM_ERROR_CODE_136', 'Смена превысила 24 часа');
define('KKM_ERROR_CODE_137', 'Открыт чек продажи – операция невозможна');
define('KKM_ERROR_CODE_140', 'Неверный пароль');
define('KKM_ERROR_CODE_143', 'Обнуленная касса (повторное гашение невозможно)');
define('KKM_ERROR_CODE_151', 'Подсчет суммы сдачи невозможен');
define('KKM_ERROR_CODE_152', 'В ККМ нет денег для выплаты');
define('KKM_ERROR_CODE_154', 'Чек закрыт – операция невозможна');
define('KKM_ERROR_CODE_155', 'Чек открыт – операция невозможна');
define('KKM_ERROR_CODE_156', 'Смена открыта, операция невозможна');
define('KKM_ERROR_CODE_157', 'ККМ заблокирована, ждет ввода пароля доступа к ФП');
define('KKM_ERROR_CODE_163', 'Неверный тип отчета');
define('KKM_ERROR_CODE_176', 'Требуется выполнение общего гашения');
define('KKM_ERROR_CODE_177', 'Команда не разрешена введенными кодами защиты ККМ');
define('KKM_ERROR_CODE_209', 'Перегрев головки принтера');
define('KKM_ERROR_CODE_216', 'ЭКЛЗ переполнена');
#define('KKM_ERROR_CODE_', '');